# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        vue-version: [3.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use vue.js ${{ matrix.vue-version }}
      uses: actions/setup-node@v3
      with:
        vue-version: ${{ matrix.vue-version }}
        cache: 'npm'
    - run: vue-cli-service serve
    - run: vue-cli-service build --if-present
    - run: vue-cli-service lint
